"""Finish-probability calibration contracts for RFS Monte Carlo V2.

These contracts define how simulated segment activity will eventually convert
into KO/TKO and submission probabilities.

No production defaults are supplied. Callers must provide an explicitly
calibrated bundle.

Planned KO/TKO probability structure:

1. Build an event hazard from landed strikes, knockdowns, and damaging clinch
   events.
2. Amplify that hazard using the defender's fatigue, persistent damage, and
   acute stress.
3. Cap the resulting segment probability.

Planned submission probability structure:

1. Begin with a probability per simulated submission attempt.
2. Adjust for ground position quality and effective submission defense.
3. Amplify using the defender's fatigue, persistent damage, and acute stress.
4. Convert attempt probability to segment probability.
5. Cap the resulting segment probability.
"""

from __future__ import annotations

import math
from dataclasses import dataclass


def _validate_unit_interval(
    name: str,
    value: float,
) -> None:
    """Validate one finite numeric value constrained to [0, 1]."""

    if not isinstance(value, (int, float)):
        raise TypeError(
            f"{name} must be numeric"
        )

    selected = float(value)

    if not math.isfinite(selected):
        raise ValueError(
            f"{name} must be finite"
        )

    if not 0.0 <= selected <= 1.0:
        raise ValueError(
            f"{name} must be between 0 and 1"
        )


@dataclass(frozen=True)
class KnockoutFinishCalibration:
    """Calibration governing segment-level KO/TKO conversion.

    Event probabilities are incremental hazards generated by simulated
    offensive events.

    ``distance_landed_probability``:
        KO/TKO hazard added by each landed distance significant strike.

    ``distance_knockdown_probability``:
        Additional KO/TKO hazard added by each distance knockdown. Knockdowns
        are already associated with landed strikes, so this is an incremental
        conversion hazard rather than a replacement for landed-strike hazard.

    ``clinch_landed_probability``:
        KO/TKO hazard added by each landed clinch significant strike.

    ``damaging_clinch_probability``:
        Additional hazard produced by a damaging clinch event.

    ``ground_landed_probability``:
        KO/TKO hazard added by each landed ground significant strike.

    Dynamic-state amplifiers increase the event hazard according to the
    defending fighter's current state.

    ``maximum_segment_probability`` caps the final probability that one
    fighter produces a KO/TKO during a single segment.
    """

    distance_landed_probability: float
    distance_knockdown_probability: float

    clinch_landed_probability: float
    damaging_clinch_probability: float

    ground_landed_probability: float

    defender_fatigue_amplifier: float
    defender_damage_amplifier: float
    defender_acute_stress_amplifier: float

    maximum_segment_probability: float

    def __post_init__(self) -> None:
        """Validate every KO/TKO calibration value."""

        for name, value in vars(self).items():
            _validate_unit_interval(
                name,
                value,
            )


@dataclass(frozen=True)
class SubmissionFinishCalibration:
    """Calibration governing segment-level submission conversion.

    ``base_probability_per_attempt``:
        Unadjusted finish probability for each simulated submission attempt.

    ``position_quality_amplifier``:
        Increases attempt probability according to authoritative ground
        position quality.

    ``minimum_submission_defense_effect_multiplier``:
        Floor applied to the effect of effective submission defense. This
        prevents maximum defense from creating complete submission immunity.

    Dynamic-state amplifiers increase attempt probability according to the
    defending fighter's current fatigue, persistent damage, and acute stress.

    ``maximum_probability_per_attempt`` caps an adjusted individual attempt.

    ``maximum_segment_probability`` caps the combined probability from every
    submission attempt generated during the segment.
    """

    base_probability_per_attempt: float
    position_quality_amplifier: float

    minimum_submission_defense_effect_multiplier: float

    defender_fatigue_amplifier: float
    defender_damage_amplifier: float
    defender_acute_stress_amplifier: float

    maximum_probability_per_attempt: float
    maximum_segment_probability: float

    def __post_init__(self) -> None:
        """Validate every submission calibration value."""

        for name, value in vars(self).items():
            _validate_unit_interval(
                name,
                value,
            )


@dataclass(frozen=True)
class FinishProbabilityCalibration:
    """Complete explicit finish-probability calibration bundle."""

    knockout: KnockoutFinishCalibration
    submission: SubmissionFinishCalibration

    def __post_init__(self) -> None:
        """Validate nested finish-calibration contracts."""

        if not isinstance(
            self.knockout,
            KnockoutFinishCalibration,
        ):
            raise TypeError(
                "knockout must be KnockoutFinishCalibration"
            )

        if not isinstance(
            self.submission,
            SubmissionFinishCalibration,
        ):
            raise TypeError(
                "submission must be SubmissionFinishCalibration"
            )
