"""Promote the reviewed three-trait FSR age-modifier candidate into active config.

This script intentionally does not refit anything. It reads the exact coefficients
from ``config/fsr_age_modifiers_candidate.yaml`` generated by the calibration
step, keeps only the reviewed age-sensitive traits active, disables every other
age rule, and writes ``config/fsr_age_modifiers.yaml``.

Locked active age-sensitive traits:
- striking_power
- knockdown_resistance
- damage_durability

Stored FSR remains immutable; these are fight-night effective modifiers only.
"""
from __future__ import annotations

from copy import deepcopy
from pathlib import Path

import yaml


CANDIDATE_PATH = Path("config/fsr_age_modifiers_candidate.yaml")
ACTIVE_PATH = Path("config/fsr_age_modifiers.yaml")
LOCKED_TRAITS = {
    "striking_power",
    "knockdown_resistance",
    "damage_durability",
}


def main() -> None:
    if not CANDIDATE_PATH.exists():
        raise FileNotFoundError(
            f"candidate config not found: {CANDIDATE_PATH}. "
            "Run calibrate_fsr_age_modifiers.py first."
        )

    with CANDIDATE_PATH.open("r", encoding="utf-8") as fh:
        candidate = yaml.safe_load(fh)
    if not isinstance(candidate, dict) or not isinstance(candidate.get("traits"), dict):
        raise RuntimeError("candidate age-modifier config is malformed")

    promoted = deepcopy(candidate)
    promoted["name"] = "fsr_age_modifiers_v1_three_trait_lock"
    promoted["promotion"] = {
        "status": "locked_shadow_candidate",
        "active_traits": sorted(LOCKED_TRAITS),
        "reason": (
            "Only traits with material FSR-scale age effects retained. "
            "Striking-power age term also improved chronological held-out log loss, "
            "Brier score, and AUC versus the same no-age model."
        ),
    }

    missing = sorted(LOCKED_TRAITS - set(promoted["traits"]))
    if missing:
        raise RuntimeError(f"candidate config missing locked traits: {missing}")

    for trait, rule in promoted["traits"].items():
        if not isinstance(rule, dict):
            continue
        if trait in LOCKED_TRAITS:
            if not bool(rule.get("calibrated", False)):
                raise RuntimeError(f"locked trait is not calibrated in candidate: {trait}")
            if "coefficients" not in rule:
                raise RuntimeError(f"locked trait missing coefficients: {trait}")
            rule["enabled"] = True
            rule["status"] = "locked_three_trait_age_modifier"
        else:
            rule["enabled"] = False
            # Preserve calibration metadata for auditability but guarantee no simulator effect.
            if str(rule.get("status", "")).startswith("population_age_calibrated"):
                rule["status"] = "calibrated_but_rejected_immaterial_age_effect"

    with ACTIVE_PATH.open("w", encoding="utf-8") as fh:
        yaml.safe_dump(promoted, fh, sort_keys=False, allow_unicode=True)

    print("FSR AGE MODIFIER PROMOTION")
    print("=" * 88)
    print(f"candidate: {CANDIDATE_PATH}")
    print(f"active:    {ACTIVE_PATH}")
    print("active traits:")
    for trait in sorted(LOCKED_TRAITS):
        rule = promoted["traits"][trait]
        coeff = rule["coefficients"]
        print(
            f"  {trait}: model={rule.get('model')} | "
            f"intercept={float(coeff.get('intercept', 0.0)):.8f} | "
            f"linear={float(coeff.get('linear', 0.0)):.8f} | "
            f"quadratic={float(coeff.get('quadratic', 0.0)):.8f} | "
            f"cubic={float(coeff.get('cubic', 0.0)):.8f}"
        )
    print("all other traits: disabled")


if __name__ == "__main__":
    main()
