from dataclasses import asdict, dataclass

import numpy as np
import pandas as pd

from pipeline.common.booleans import coerce_bool


STATUS_ORDER = [
    "OFFICIAL BET",
    "WATCHLIST",
    "LOW ODDS MATCH",
    "SPARSE FEATURES",
    "INVALID MODEL DATA",
    "NO BET",
]

SCENARIO_FILTER_COLUMNS = [
    "scenario_passes_model_quality_filter",
    "scenario_passes_feature_validation_filter",
    "scenario_passes_odds_match_filter",
    "scenario_passes_edge_filter",
    "scenario_passes_confidence_filter",
    "scenario_passes_odds_range_filter",
    "scenario_passes_positive_ev_filter",
]

SCENARIO_BETTING_THRESHOLD_COLUMNS = [
    "scenario_passes_edge_filter",
    "scenario_passes_confidence_filter",
    "scenario_passes_odds_range_filter",
    "scenario_passes_positive_ev_filter",
]


@dataclass(frozen=True)
class BettingRules:
    min_edge: float = 0.05
    min_confidence: float = 70.0
    min_odds: int = -250
    max_odds: int = 400
    require_positive_ev: bool = True
    watchlist_max_failed_thresholds: int = 2
    watchlist_high_ev_override: float = 0.25
    bankroll: float = 10000.0
    kelly_fraction: float = 0.50
    max_stake_pct: float = 1.0
    min_stake: float = 0.0
    stake_rounding: float = 1.0


def default_betting_rules() -> BettingRules:
    return BettingRules()


def rules_to_dict(rules: BettingRules) -> dict:
    return asdict(rules)


def rules_changed_from_default(rules: BettingRules) -> bool:
    return rules_to_dict(rules) != rules_to_dict(default_betting_rules())


def american_to_decimal(odds):
    if pd.isna(odds):
        return np.nan

    odds = float(odds)

    if odds > 0:
        return 1 + odds / 100

    return 1 + 100 / abs(odds)


def american_to_implied_prob(odds):
    if pd.isna(odds):
        return np.nan

    odds = float(odds)

    if odds < 0:
        return abs(odds) / (abs(odds) + 100)

    return 100 / (odds + 100)


def decimal_ev(model_prob, decimal_odds):
    if pd.isna(model_prob) or pd.isna(decimal_odds):
        return np.nan

    decimal_odds = float(decimal_odds)
    if decimal_odds <= 1:
        return np.nan

    p = float(model_prob)
    return (p * (decimal_odds - 1)) - (1 - p)


def _norm_name(value):
    if pd.isna(value):
        return ""
    return " ".join(str(value).strip().lower().split())


def _has_value(value):
    return not pd.isna(value) and str(value).strip() != ""


def _infer_odds_match_order(row):
    explicit_order = row.get("odds_match_order")
    if _has_value(explicit_order):
        return str(explicit_order)

    matched_1 = _norm_name(row.get("matched_fighter_1"))
    matched_2 = _norm_name(row.get("matched_fighter_2"))
    red = _norm_name(row.get("red_fighter"))
    blue = _norm_name(row.get("blue_fighter"))

    if not matched_1 or not matched_2 or not red or not blue:
        return "unknown"

    if matched_1 == red and matched_2 == blue:
        return "same_order"

    if matched_1 == blue and matched_2 == red:
        return "reversed_order"

    return "unknown"


def normalize_betting_board_odds(board_df):
    """Return a display-safe board with red/blue odds mapped to UFCStats sides.

    Older generated Betting Board artifacts may contain red/blue odds assigned
    directly from sportsbook outcome order.  If market-match diagnostics show
    the sportsbook row was reversed and no explicit `odds_match_order` exists,
    swap red/blue odds in memory and recompute edge/EV/best-side fields for
    the dashboard.  New artifacts generated by the fixed market runner already
    carry side-mapped red/blue odds and an explicit `odds_match_order`, so they
    are not swapped again.
    """

    board = board_df.copy()
    if board.empty:
        board["odds_side_mapping_status"] = pd.Series(dtype="object")
        return board

    if "odds_match_order" not in board.columns:
        board["odds_match_order"] = ""

    board["odds_inferred_match_order"] = board.apply(_infer_odds_match_order, axis=1)
    has_explicit_order = board["odds_match_order"].apply(_has_value)
    needs_swap = (~has_explicit_order) & (board["odds_inferred_match_order"] == "reversed_order")

    swap_columns = [
        ("red_american_odds", "blue_american_odds"),
        ("red_decimal_odds", "blue_decimal_odds"),
        ("red_implied_prob", "blue_implied_prob"),
    ]
    for red_col, blue_col in swap_columns:
        if red_col in board.columns and blue_col in board.columns:
            red_values = board.loc[needs_swap, red_col].copy()
            board.loc[needs_swap, red_col] = board.loc[needs_swap, blue_col].values
            board.loc[needs_swap, blue_col] = red_values.values

    board["odds_side_mapping_status"] = np.select(
        [
            needs_swap,
            has_explicit_order & (board["odds_match_order"] == "reversed_order"),
            board["odds_inferred_match_order"] == "same_order",
        ],
        [
            "corrected_reversed_order",
            "already_side_mapped_reversed_order",
            "same_order",
        ],
        default="unknown",
    )

    for odds_col in ["red_american_odds", "blue_american_odds"]:
        if odds_col in board.columns:
            board[odds_col] = pd.to_numeric(board[odds_col], errors="coerce")

    if "red_american_odds" in board.columns:
        board["red_decimal_odds"] = board["red_american_odds"].apply(american_to_decimal)
        board["red_implied_prob"] = board["red_american_odds"].apply(american_to_implied_prob)
    if "blue_american_odds" in board.columns:
        board["blue_decimal_odds"] = board["blue_american_odds"].apply(american_to_decimal)
        board["blue_implied_prob"] = board["blue_american_odds"].apply(american_to_implied_prob)

    if {"red_model_prob", "red_implied_prob"}.issubset(board.columns):
        board["red_edge"] = pd.to_numeric(board["red_model_prob"], errors="coerce") - pd.to_numeric(board["red_implied_prob"], errors="coerce")
    if {"blue_model_prob", "blue_implied_prob"}.issubset(board.columns):
        board["blue_edge"] = pd.to_numeric(board["blue_model_prob"], errors="coerce") - pd.to_numeric(board["blue_implied_prob"], errors="coerce")

    if {"red_model_prob", "red_decimal_odds"}.issubset(board.columns):
        board["red_ev"] = board.apply(lambda row: decimal_ev(row.get("red_model_prob"), row.get("red_decimal_odds")), axis=1)
        board["red_ev_pct"] = board["red_ev"]
    if {"blue_model_prob", "blue_decimal_odds"}.issubset(board.columns):
        board["blue_ev"] = board.apply(lambda row: decimal_ev(row.get("blue_model_prob"), row.get("blue_decimal_odds")), axis=1)
        board["blue_ev_pct"] = board["blue_ev"]

    if {"red_ev", "blue_ev"}.issubset(board.columns):
        board["red_is_best"] = pd.to_numeric(board["red_ev"], errors="coerce") >= pd.to_numeric(board["blue_ev"], errors="coerce")
        board["best_side"] = np.where(board["red_is_best"], board.get("red_fighter"), board.get("blue_fighter"))

        if {"red_fighter_id", "blue_fighter_id"}.issubset(board.columns):
            board["best_side_fighter_id"] = np.where(board["red_is_best"], board["red_fighter_id"], board["blue_fighter_id"])
            board["best_side_opponent_id"] = np.where(board["red_is_best"], board["blue_fighter_id"], board["red_fighter_id"])

        for output_col, red_col, blue_col in [
            ("best_prob", "red_model_prob", "blue_model_prob"),
            ("best_implied_prob", "red_implied_prob", "blue_implied_prob"),
            ("best_edge", "red_edge", "blue_edge"),
            ("best_ev", "red_ev", "blue_ev"),
            ("best_ev_pct", "red_ev", "blue_ev"),
            ("best_american_odds", "red_american_odds", "blue_american_odds"),
            ("best_decimal_odds", "red_decimal_odds", "blue_decimal_odds"),
        ]:
            if red_col in board.columns and blue_col in board.columns:
                board[output_col] = np.where(board["red_is_best"], board[red_col], board[blue_col])

        if "best_prob" in board.columns:
            board["best_confidence"] = pd.to_numeric(board["best_prob"], errors="coerce") * 100

    return board


def kelly_fraction(model_prob, american_odds):
    if pd.isna(model_prob) or pd.isna(american_odds):
        return 0.0

    decimal_odds = american_to_decimal(american_odds)
    b = decimal_odds - 1
    p = float(model_prob)
    q = 1 - p

    if b <= 0:
        return 0.0

    return max(0.0, ((b * p) - q) / b)


def scaled_kelly_stake(
    bankroll,
    model_prob,
    american_odds,
    kelly_multiplier,
    max_stake_pct,
    min_stake=0.0,
    stake_rounding=1.0,
):
    full_kelly = kelly_fraction(model_prob, american_odds)
    raw_stake = float(bankroll) * full_kelly * float(kelly_multiplier)
    capped_stake = min(raw_stake, float(bankroll) * float(max_stake_pct))

    if capped_stake < float(min_stake):
        return 0.0

    if stake_rounding and float(stake_rounding) > 0:
        capped_stake = round(capped_stake / float(stake_rounding)) * float(stake_rounding)

    return round(float(capped_stake), 2)


def _bool_series(df, column, default=False):
    if column not in df.columns:
        return pd.Series(default, index=df.index)

    return df[column].apply(lambda value: coerce_bool(value, default=default))


def _numeric_series(df, column, default=np.nan):
    if column not in df.columns:
        return pd.Series(default, index=df.index, dtype="float64")

    return pd.to_numeric(df[column], errors="coerce")


def build_failed_filter_reason(row):
    failed = []

    for col in SCENARIO_FILTER_COLUMNS:
        if not row[col]:
            failed.append(
                col.replace("scenario_passes_", "")
                .replace("_filter", "")
            )

    return ", ".join(failed)


def apply_betting_rules(board_df, rules: BettingRules):
    scenario = board_df.copy()

    scenario["scenario_passes_model_quality_filter"] = _bool_series(
        scenario,
        "passes_model_quality_filter",
    )
    scenario["scenario_passes_feature_validation_filter"] = _bool_series(
        scenario,
        "passes_feature_validation_filter",
    )
    scenario["scenario_passes_odds_match_filter"] = _bool_series(
        scenario,
        "passes_odds_match_filter",
    )

    best_edge = _numeric_series(scenario, "best_edge")
    best_confidence = _numeric_series(scenario, "best_confidence")
    best_american_odds = _numeric_series(scenario, "best_american_odds")
    best_ev = _numeric_series(scenario, "best_ev")

    scenario["scenario_passes_edge_filter"] = best_edge >= rules.min_edge
    scenario["scenario_passes_confidence_filter"] = best_confidence >= rules.min_confidence
    scenario["scenario_passes_odds_range_filter"] = (
        (best_american_odds >= rules.min_odds)
        &
        (best_american_odds <= rules.max_odds)
    )
    scenario["scenario_passes_positive_ev_filter"] = (
        best_ev > 0
        if rules.require_positive_ev
        else pd.Series(True, index=scenario.index)
    )

    scenario["scenario_passes_all_bet_filters"] = scenario[SCENARIO_FILTER_COLUMNS].all(axis=1)
    scenario["scenario_failed_filter_count"] = (
        len(SCENARIO_FILTER_COLUMNS)
        - scenario[SCENARIO_FILTER_COLUMNS].sum(axis=1)
    )
    scenario["scenario_failed_filters"] = scenario.apply(
        build_failed_filter_reason,
        axis=1,
    )

    scenario["scenario_passes_core_data_filters"] = (
        scenario["scenario_passes_model_quality_filter"]
        &
        scenario["scenario_passes_feature_validation_filter"]
        &
        scenario["scenario_passes_odds_match_filter"]
    )

    scenario["scenario_failed_betting_threshold_count"] = (
        len(SCENARIO_BETTING_THRESHOLD_COLUMNS)
        - scenario[SCENARIO_BETTING_THRESHOLD_COLUMNS].sum(axis=1)
    )

    scenario["scenario_is_official_bet"] = scenario["scenario_passes_all_bet_filters"]
    scenario["scenario_is_watchlist_bet"] = (
        (~scenario["scenario_is_official_bet"])
        &
        scenario["scenario_passes_core_data_filters"]
        &
        (
            (scenario["scenario_failed_betting_threshold_count"] <= rules.watchlist_max_failed_thresholds)
            |
            (best_ev > rules.watchlist_high_ev_override)
        )
    )

    scenario["scenario_recommended_stake"] = scenario.apply(
        lambda row: scaled_kelly_stake(
            bankroll=rules.bankroll,
            model_prob=row.get("best_prob"),
            american_odds=row.get("best_american_odds"),
            kelly_multiplier=rules.kelly_fraction,
            max_stake_pct=rules.max_stake_pct,
            min_stake=rules.min_stake,
            stake_rounding=rules.stake_rounding,
        )
        if row["scenario_passes_all_bet_filters"]
        else 0.0,
        axis=1,
    )

    scenario["scenario_bet_status"] = "NO BET"
    scenario.loc[
        ~scenario["scenario_passes_model_quality_filter"],
        "scenario_bet_status",
    ] = "INVALID MODEL DATA"
    scenario.loc[
        scenario["scenario_passes_model_quality_filter"]
        &
        ~scenario["scenario_passes_feature_validation_filter"],
        "scenario_bet_status",
    ] = "SPARSE FEATURES"
    scenario.loc[
        scenario["scenario_passes_model_quality_filter"]
        &
        scenario["scenario_passes_feature_validation_filter"]
        &
        ~scenario["scenario_passes_odds_match_filter"],
        "scenario_bet_status",
    ] = "LOW ODDS MATCH"
    scenario.loc[
        scenario["scenario_is_watchlist_bet"],
        "scenario_bet_status",
    ] = "WATCHLIST"
    scenario.loc[
        scenario["scenario_is_official_bet"],
        "scenario_bet_status",
    ] = "OFFICIAL BET"

    scenario["scenario_bet_reason"] = np.where(
        scenario["scenario_is_official_bet"],
        "All scenario betting filters passed",
        scenario["scenario_failed_filters"],
    )

    return scenario


def scenario_comparison(board_df, scenario_df):
    production_status = board_df.get("bet_status", pd.Series(index=board_df.index, dtype="object"))
    scenario_status = scenario_df.get("scenario_bet_status", pd.Series(index=scenario_df.index, dtype="object"))
    production_stake = _numeric_series(board_df, "recommended_stake", default=0).fillna(0)
    scenario_stake = _numeric_series(scenario_df, "scenario_recommended_stake", default=0).fillna(0)

    return {
        "production_official_bets": int((production_status == "OFFICIAL BET").sum()),
        "scenario_official_bets": int((scenario_status == "OFFICIAL BET").sum()),
        "production_watchlist": int((production_status == "WATCHLIST").sum()),
        "scenario_watchlist": int((scenario_status == "WATCHLIST").sum()),
        "production_total_stake": float(production_stake.sum()),
        "scenario_total_stake": float(scenario_stake.sum()),
        "added_official_bets": int(((production_status != "OFFICIAL BET") & (scenario_status == "OFFICIAL BET")).sum()),
        "removed_official_bets": int(((production_status == "OFFICIAL BET") & (scenario_status != "OFFICIAL BET")).sum()),
        "stake_delta": float(scenario_stake.sum() - production_stake.sum()),
    }
