"""Shadow-validate the generic feature builder against moneyline_feature_view.

This one-off migration script compares feature columns generated by the generic
feature builder against the existing validated moneyline feature view.

Run from repo root:

    python -m archive.migration_validation.run_shadow_generic_feature_builder
"""

from __future__ import annotations

import numpy as np
import pandas as pd

from pipeline.features.feature_graph import resolve_feature_graph_plan
from pipeline.features.generic_feature_builder import build_generic_features_from_plan


FEATURE_VIEW_PATH = "data/features/moneyline_feature_view.parquet"
FEATURE_VIEW_CONFIG_PATH = "configs/feature_views/moneyline_base.yaml"


# Restrict v1 shadow validation to current production-like columns that already
# exist in moneyline_feature_view. Ratio and abs-gap candidates are intentionally
# excluded here unless they already exist in the source view.
VALIDATE_SUFFIXES = (
    "_diff",
    "_abs_gap",
    "_ratio",
)


def main() -> None:
    """Run shadow comparison."""

    print("=" * 80)
    print("GENERIC FEATURE BUILDER SHADOW VALIDATION")
    print("=" * 80)
    print(f"Feature view path  : {FEATURE_VIEW_PATH}")
    print(f"Feature config path: {FEATURE_VIEW_CONFIG_PATH}")

    df = pd.read_parquet(FEATURE_VIEW_PATH)
    print(f"Input shape        : {df.shape}")

    plan = resolve_feature_graph_plan(FEATURE_VIEW_CONFIG_PATH)
    print(f"Graph generated cols: {len(plan.generated_feature_columns)}")
    print(f"Graph passthrough   : {len(plan.passthrough_feature_columns)}")

    result = build_generic_features_from_plan(df=df, plan=plan)
    print(f"Builder generated   : {len(result.generated_columns)}")
    print(f"Missing source pairs: {len(result.missing_source_pairs)}")

    overlap_columns = [
        column
        for column in result.generated_columns
        if column in df.columns and column.endswith(VALIDATE_SUFFIXES)
    ]

    print(f"Overlap columns     : {len(overlap_columns)}")
    if not overlap_columns:
        raise SystemExit("No overlapping generated columns found for shadow validation.")

    rows = []
    for column in overlap_columns:
        old_values = pd.to_numeric(df[column], errors="coerce")
        new_values = pd.to_numeric(result.dataframe[column], errors="coerce")
        delta = (old_values - new_values).abs()
        comparable = delta.dropna()

        max_abs_diff = float(comparable.max()) if len(comparable) else 0.0
        mean_abs_diff = float(comparable.mean()) if len(comparable) else 0.0
        nonzero_rows = int((comparable > 1e-9).sum())
        status = "PASS" if nonzero_rows == 0 else "FAIL_VALUE_MISMATCH"

        rows.append(
            {
                "feature_name": column,
                "status": status,
                "max_abs_diff": max_abs_diff,
                "mean_abs_diff": mean_abs_diff,
                "nonzero_rows": nonzero_rows,
            }
        )

    audit_df = pd.DataFrame(rows).sort_values(["status", "feature_name"])
    status_counts = audit_df["status"].value_counts()

    print("\nStatus counts:")
    print(status_counts.to_string())

    failures = audit_df[audit_df["status"] != "PASS"]
    if not failures.empty:
        print("\nFailures:")
        print(failures.head(50).to_string(index=False))
        raise SystemExit("Generic feature builder shadow validation failed.")

    print("\nValidated columns:")
    print(audit_df["feature_name"].head(80).to_string(index=False))
    if len(audit_df) > 80:
        print(f"... {len(audit_df) - 80} more")

    print("DONE")


if __name__ == "__main__":
    main()
