"""Thirty-second activity generation for RFS Monte Carlo V1.

Phase 3 scope:
- choose a fight phase
- generate activity counts for one 30-second segment
- use explicit NumPy random generators
- return immutable segment results

Out of scope:
- dynamic fatigue and damage updates
- finish hazards
- round scoring
- file I/O
- production integration
"""

from __future__ import annotations

from dataclasses import dataclass, replace
from typing import Mapping

import numpy as np

from pipeline.simulation.rfs_mc_v1.contracts import (
    FightPhase,
    FighterSimulationProfile,
)


SEGMENT_SECONDS = 30
SEGMENTS_PER_ROUND = 10


class SegmentEngineError(ValueError):
    """Raised when segment inputs are invalid."""


@dataclass(frozen=True)
class SegmentActivity:
    """Activity generated by one fighter during one 30-second segment."""

    phase: FightPhase

    sig_str_attempted: int
    sig_str_landed: int

    td_attempted: int
    td_landed: int

    control_seconds: int

    ground_str_attempted: int
    ground_str_landed: int

    submission_attempts: int
    knockdowns: int

    def __post_init__(self) -> None:
        integer_fields = {
            "sig_str_attempted": self.sig_str_attempted,
            "sig_str_landed": self.sig_str_landed,
            "td_attempted": self.td_attempted,
            "td_landed": self.td_landed,
            "control_seconds": self.control_seconds,
            "ground_str_attempted": self.ground_str_attempted,
            "ground_str_landed": self.ground_str_landed,
            "submission_attempts": self.submission_attempts,
            "knockdowns": self.knockdowns,
        }

        for name, value in integer_fields.items():
            if value < 0:
                raise ValueError(f"{name} cannot be negative")

        if self.sig_str_landed > self.sig_str_attempted:
            raise ValueError(
                "sig_str_landed cannot exceed sig_str_attempted"
            )

        if self.td_landed > self.td_attempted:
            raise ValueError("td_landed cannot exceed td_attempted")

        if self.ground_str_landed > self.ground_str_attempted:
            raise ValueError(
                "ground_str_landed cannot exceed ground_str_attempted"
            )

        if (
            self.submission_attempts > 0
            and self.phase != FightPhase.GROUND
            and self.control_seconds <= 0
        ):
            raise ValueError(
                "submission attempts require ground phase "
                "or positive control time"
            )

        if self.control_seconds > SEGMENT_SECONDS:
            raise ValueError(
                f"control_seconds cannot exceed {SEGMENT_SECONDS}"
            )


@dataclass(frozen=True)
class SegmentMatchupActivity:
    """Red and blue activity generated for the same segment."""

    round_number: int
    segment_number: int
    red: SegmentActivity
    blue: SegmentActivity

    def __post_init__(self) -> None:
        if self.round_number <= 0:
            raise ValueError("round_number must be positive")

        if not 1 <= self.segment_number <= SEGMENTS_PER_ROUND:
            raise ValueError(
                f"segment_number must be between 1 and "
                f"{SEGMENTS_PER_ROUND}"
            )


@dataclass(frozen=True)
class ActivityParameters:
    """Directly interpretable parameters used by the activity generator."""

    distance_phase_probability: float
    clinch_phase_probability: float
    ground_phase_probability: float

    sig_attempt_rate: float
    sig_accuracy: float

    td_attempt_rate: float
    td_accuracy: float

    control_probability: float
    mean_control_seconds: float

    ground_attempt_rate: float
    ground_accuracy: float

    submission_attempt_rate: float
    knockdown_probability: float

    def __post_init__(self) -> None:
        probabilities = {
            "distance_phase_probability": (
                self.distance_phase_probability
            ),
            "clinch_phase_probability": self.clinch_phase_probability,
            "ground_phase_probability": self.ground_phase_probability,
            "sig_accuracy": self.sig_accuracy,
            "td_accuracy": self.td_accuracy,
            "control_probability": self.control_probability,
            "ground_accuracy": self.ground_accuracy,
            "knockdown_probability": self.knockdown_probability,
        }

        for name, value in probabilities.items():
            if not 0.0 <= value <= 1.0:
                raise ValueError(f"{name} must be between 0 and 1")

        phase_total = (
            self.distance_phase_probability
            + self.clinch_phase_probability
            + self.ground_phase_probability
        )

        if not np.isclose(phase_total, 1.0):
            raise ValueError(
                "phase probabilities must sum to 1"
            )

        nonnegative = {
            "sig_attempt_rate": self.sig_attempt_rate,
            "td_attempt_rate": self.td_attempt_rate,
            "mean_control_seconds": self.mean_control_seconds,
            "ground_attempt_rate": self.ground_attempt_rate,
            "submission_attempt_rate": self.submission_attempt_rate,
        }

        for name, value in nonnegative.items():
            if value < 0:
                raise ValueError(f"{name} cannot be negative")


DEFAULT_ACTIVITY_PARAMETERS = ActivityParameters(
    distance_phase_probability=0.70,
    clinch_phase_probability=0.15,
    ground_phase_probability=0.15,
    sig_attempt_rate=4.0,
    sig_accuracy=0.45,
    td_attempt_rate=0.30,
    td_accuracy=0.35,
    control_probability=0.30,
    mean_control_seconds=12.0,
    ground_attempt_rate=1.5,
    ground_accuracy=0.50,
    submission_attempt_rate=0.08,
    knockdown_probability=0.015,
)


def _profile_value(
    profile: FighterSimulationProfile,
    name: str,
    *,
    default: float,
) -> float:
    """Read one optional profile value without mutating the profile."""

    estimate = profile.parameters.get(name)
    if estimate is None:
        return default

    value = float(estimate.value)

    if not np.isfinite(value):
        raise SegmentEngineError(
            f"Profile parameter {name!r} is not finite"
        )

    return value


def build_activity_parameters(
    profile: FighterSimulationProfile,
    *,
    round_number: int = 1,
) -> ActivityParameters:
    """Map a fighter profile into initial segment activity parameters.

    These mappings are deliberately conservative placeholders for Phase 3.
    They establish testable mechanics contracts but are not calibrated final
    coefficients.
    """

    phase_disruption = _profile_value(
        profile,
        "phase_mix_disruption",
        default=0.0,
    )
    wrestling_persistence = _profile_value(
        profile,
        "wrestling_persistence",
        default=0.0,
    )
    sig_attempt_trajectory = _profile_value(
        profile,
        "sig_attempt_trajectory",
        default=0.0,
    )
    sig_accuracy_trajectory = _profile_value(
        profile,
        "sig_accuracy_trajectory",
        default=0.0,
    )
    late_td_output_ratio = _profile_value(
        profile,
        "late_td_output_ratio",
        default=1.0,
    )
    control_per_td_attempt = _profile_value(
        profile,
        "control_per_td_attempt",
        default=0.0,
    )
    control_to_damage = _profile_value(
        profile,
        "control_to_damage",
        default=0.0,
    )
    submission_pressure = _profile_value(
        profile,
        "submission_pressure",
        default=0.0,
    )
    opening_sig_attempts_per_min = _profile_value(
        profile,
        "opening_sig_attempts",
        default=8.0,
    )
    opening_sig_landed_per_min = _profile_value(
        profile,
        "opening_sig_landed",
        default=3.6,
    )
    opening_kd_per_sig_landed = _profile_value(
        profile,
        "opening_kd_per_sig_landed",
        default=_profile_value(
            profile,
            "offensive_kd_per_sig_landed",
            default=0.015,
        ),
    )

    opening_kd_estimate = profile.parameters.get(
        "opening_kd_per_sig_landed"
    )
    opening_kd_sample_size = (
        float(opening_kd_estimate.effective_sample_size)
        if opening_kd_estimate is not None
        else 0.0
    )
    late_sig_output_ratio = _profile_value(
        profile,
        "late_sig_output_ratio",
        default=1.0,
    )

    # RFS inputs have different natural scales. Convert them through
    # bounded transforms rather than treating raw values as direct rates.
    wrestling_signal = float(
        np.tanh(wrestling_persistence / 10.0)
    )
    phase_signal = float(
        np.tanh(phase_disruption / 10.0)
    )

    ground_probability = float(
        np.clip(
            0.15
            + 0.06 * wrestling_signal
            + 0.02 * phase_signal,
            0.08,
            0.30,
        )
    )

    clinch_probability = float(
        np.clip(
            0.15 + 0.03 * phase_signal,
            0.10,
            0.22,
        )
    )

    distance_probability = 1.0 - (
        ground_probability + clinch_probability
    )

    if distance_probability < 0.05:
        excess = 0.05 - distance_probability
        ground_probability = max(
            0.05,
            ground_probability - excess,
        )
        distance_probability = 0.05

    phase_total = (
        distance_probability
        + clinch_probability
        + ground_probability
    )

    distance_probability /= phase_total
    clinch_probability /= phase_total
    ground_probability /= phase_total

    trajectory_signal = float(
        np.tanh(sig_attempt_trajectory / 20.0)
    )
    accuracy_signal = float(
        np.tanh(sig_accuracy_trajectory / 10.0)
    )
    control_signal = float(
        np.tanh(control_per_td_attempt / 60.0)
    )
    damage_conversion_signal = float(
        np.tanh(control_to_damage / 10.0)
    )
    submission_signal = float(
        np.tanh(submission_pressure / 5.0)
    )
    late_td_signal = float(
        np.tanh(
            (late_td_output_ratio - 1.0)
            / 0.50
        )
    )
    if round_number <= 0:
        raise SegmentEngineError(
            "round_number must be positive"
        )

    # Opening rates are stored per minute. Each simulation segment lasts
    # thirty seconds, so divide by two for the segment Poisson mean.
    opening_sig_attempt_rate = float(
        np.clip(
            opening_sig_attempts_per_min / 2.0,
            1.0,
            8.0,
        )
    )

    if opening_sig_attempts_per_min > 0:
        opening_sig_accuracy = float(
            np.clip(
                opening_sig_landed_per_min
                / opening_sig_attempts_per_min,
                0.20,
                0.75,
            )
        )
    else:
        opening_sig_accuracy = 0.45

    # Trajectory changes the fighter after the opening round rather than
    # defining the opening baseline.
    round_progress = {
        1: 0.00,
        2: 0.35,
        3: 0.65,
        4: 0.85,
        5: 1.00,
    }.get(round_number, 1.00)

    late_output_signal = float(
        np.tanh(
            (late_sig_output_ratio - 1.0)
            / 0.50
        )
    )

    sustained_rate_multiplier = float(
        np.clip(
            1.0
            + 0.35 * trajectory_signal
            + 0.25 * late_output_signal,
            0.45,
            1.60,
        )
    )

    sustained_sig_attempt_rate = (
        opening_sig_attempt_rate
        * sustained_rate_multiplier
    )

    sig_attempt_rate = float(
        np.clip(
            opening_sig_attempt_rate
            + round_progress
            * (
                sustained_sig_attempt_rate
                - opening_sig_attempt_rate
            ),
            1.0,
            8.0,
        )
    )

    sustained_sig_accuracy = float(
        np.clip(
            opening_sig_accuracy
            + 0.08 * accuracy_signal,
            0.20,
            0.75,
        )
    )

    sig_accuracy = float(
        np.clip(
            opening_sig_accuracy
            + round_progress
            * (
                sustained_sig_accuracy
                - opening_sig_accuracy
            ),
            0.20,
            0.75,
        )
    )

    # Opening takedown pressure comes from wrestling persistence.
    # Later rounds blend toward the fighter's observed late takedown output.
    opening_td_attempt_rate = float(
        np.clip(
            0.30 + 0.18 * wrestling_signal,
            0.08,
            0.60,
        )
    )

    sustained_td_multiplier = float(
        np.clip(
            1.0 + 0.60 * late_td_signal,
            0.40,
            1.60,
        )
    )

    sustained_td_attempt_rate = (
        opening_td_attempt_rate
        * sustained_td_multiplier
    )

    td_attempt_rate = float(
        np.clip(
            opening_td_attempt_rate
            + round_progress
            * (
                sustained_td_attempt_rate
                - opening_td_attempt_rate
            ),
            0.05,
            0.80,
        )
    )

    mean_control_seconds = float(
        np.clip(
            8.0 + 4.0 * control_signal,
            4.0,
            12.0,
        )
    )

    ground_attempt_rate = float(
        np.clip(
            1.5 + 1.0 * damage_conversion_signal,
            0.5,
            2.5,
        )
    )

    # Fighter-level tendency to pursue submissions after reaching
    # a viable ground or control position. Current position quality is
    # applied separately inside the segment generator.
    submission_attempt_rate = float(
        np.clip(
            0.10 + 0.20 * submission_signal,
            0.05,
            0.35,
        )
    )

    # Preserve the fighter-specific observed power signal.
    # Path-specific energy and matchup pressure modify this value later.
    knockdown_probability = float(
        np.clip(
            opening_kd_per_sig_landed,
            0.001,
            0.060,
        )
    )

    return ActivityParameters(
        distance_phase_probability=distance_probability,
        clinch_phase_probability=clinch_probability,
        ground_phase_probability=ground_probability,
        sig_attempt_rate=sig_attempt_rate,
        sig_accuracy=sig_accuracy,
        td_attempt_rate=td_attempt_rate,
        td_accuracy=0.35,
        control_probability=0.30,
        mean_control_seconds=mean_control_seconds,
        ground_attempt_rate=ground_attempt_rate,
        ground_accuracy=0.50,
        submission_attempt_rate=submission_attempt_rate,
        knockdown_probability=knockdown_probability,
    )


def sample_phase(
    parameters: ActivityParameters,
    rng: np.random.Generator,
) -> FightPhase:
    """Sample the dominant phase for one fighter in one segment."""

    phases = np.array(
        [
            FightPhase.DISTANCE,
            FightPhase.CLINCH,
            FightPhase.GROUND,
        ],
        dtype=object,
    )

    probabilities = np.array(
        [
            parameters.distance_phase_probability,
            parameters.clinch_phase_probability,
            parameters.ground_phase_probability,
        ],
        dtype=float,
    )

    return rng.choice(phases, p=probabilities)


def generate_segment_activity(
    parameters: ActivityParameters,
    rng: np.random.Generator,
) -> SegmentActivity:
    """Generate one fighter's activity for one 30-second segment."""

    phase = sample_phase(parameters, rng)

    sig_multiplier = {
        FightPhase.DISTANCE: 1.00,
        FightPhase.CLINCH: 0.65,
        FightPhase.GROUND: 0.35,
    }[phase]

    td_multiplier = {
        FightPhase.DISTANCE: 0.70,
        FightPhase.CLINCH: 1.40,
        FightPhase.GROUND: 0.15,
    }[phase]

    sig_attempted = int(
        rng.poisson(
            parameters.sig_attempt_rate * sig_multiplier
        )
    )

    sig_str_landed = int(
        rng.binomial(
            sig_attempted,
            parameters.sig_accuracy,
        )
    )

    td_attempted = int(
        rng.poisson(
            parameters.td_attempt_rate * td_multiplier
        )
    )

    td_landed = int(
        rng.binomial(
            td_attempted,
            parameters.td_accuracy,
        )
    )

    control_seconds = 0
    if (
        phase is FightPhase.GROUND
        or td_landed > 0
    ) and rng.random() < parameters.control_probability:
        sampled_control = rng.exponential(
            parameters.mean_control_seconds
        )
        control_seconds = int(
            np.clip(
                round(sampled_control),
                0,
                SEGMENT_SECONDS,
            )
        )

    ground_str_attempted = 0
    ground_str_landed = 0
    submission_attempts = 0

    submission_eligible = (
        phase == FightPhase.GROUND
        or control_seconds > 0
    )

    if submission_eligible:
        ground_str_attempted = int(
            rng.poisson(parameters.ground_attempt_rate)
        )
        ground_str_landed = int(
            rng.binomial(
                ground_str_attempted,
                parameters.ground_accuracy,
            )
        )
        submission_attempts = _sample_submission_attempts(
            parameters=parameters,
            phase=phase,
            control_seconds=control_seconds,
            td_landed=td_landed,
            rng=rng,
        )

    knockdowns = int(
        rng.binomial(
            sig_str_landed,
            parameters.knockdown_probability,
        )
    )

    return SegmentActivity(
        phase=phase,
        sig_str_attempted=sig_attempted,
        sig_str_landed=sig_str_landed,
        td_attempted=td_attempted,
        td_landed=td_landed,
        control_seconds=control_seconds,
        ground_str_attempted=ground_str_attempted,
        ground_str_landed=ground_str_landed,
        submission_attempts=submission_attempts,
        knockdowns=knockdowns,
    )


def _submission_attempt_lambda(
    *,
    parameters: ActivityParameters,
    phase: FightPhase,
    control_seconds: int,
    td_landed: int,
) -> float:
    """Return the Poisson rate for one submission opportunity.

    Attempts are impossible without a ground phase or positive control.
    Viable positions become more dangerous with longer control and a
    takedown completed during the segment.
    """

    eligible = (
        phase == FightPhase.GROUND
        or control_seconds > 0
    )

    if not eligible:
        return 0.0

    control_fraction = float(
        np.clip(
            control_seconds / SEGMENT_SECONDS,
            0.0,
            1.0,
        )
    )

    # Ground position supplies a stronger baseline than incidental
    # clinch control. Sustained control and a fresh takedown increase
    # the quality of the opportunity.
    phase_quality = (
        0.75
        if phase == FightPhase.GROUND
        else 0.50
    )

    position_quality = (
        phase_quality
        + control_fraction
        + (0.20 if td_landed > 0 else 0.0)
    )

    return float(
        np.clip(
            parameters.submission_attempt_rate
            * position_quality,
            0.0,
            0.75,
        )
    )


def _sample_submission_attempts(
    *,
    parameters: ActivityParameters,
    phase: FightPhase,
    control_seconds: int,
    td_landed: int,
    rng: np.random.Generator,
) -> int:
    """Sample attempts only from an eligible grappling position."""

    attempt_lambda = _submission_attempt_lambda(
        parameters=parameters,
        phase=phase,
        control_seconds=control_seconds,
        td_landed=td_landed,
    )

    if attempt_lambda <= 0.0:
        return 0

    return int(rng.poisson(attempt_lambda))


def _round_progress(round_number: int) -> float:
    """Return bounded progress from the opening round to late fight."""

    return {
        1: 0.00,
        2: 0.35,
        3: 0.65,
        4: 0.85,
        5: 1.00,
    }.get(round_number, 1.00)


def _effective_td_accuracy(
    *,
    attacker_profile: FighterSimulationProfile,
    defender_profile: FighterSimulationProfile,
    base_accuracy: float,
    round_number: int,
) -> float:
    """Resolve attacker takedown offense against defender resistance."""

    wrestling_persistence = _profile_value(
        attacker_profile,
        "wrestling_persistence",
        default=0.0,
    )
    td_to_control_conversion = _profile_value(
        attacker_profile,
        "td_to_control_conversion",
        default=0.0,
    )

    # Suppression deltas are opponent-relative. Negative opponent accuracy
    # deltas indicate that this defender historically reduced TD accuracy.
    opponent_td_accuracy_suppression = _profile_value(
        defender_profile,
        "opponent_td_accuracy_suppression",
        default=0.0,
    )
    late_td_defense_decay = _profile_value(
        defender_profile,
        "late_td_defense_decay",
        default=0.0,
    )

    attacker_signal = float(
        np.tanh(
            wrestling_persistence / 10.0
            + td_to_control_conversion / 10.0
        )
    )

    defender_resistance_signal = float(
        np.tanh(
            -opponent_td_accuracy_suppression / 0.20
        )
    )

    defense_decay_signal = float(
        np.tanh(late_td_defense_decay / 0.20)
    )

    effective_accuracy = (
        base_accuracy
        + 0.10 * attacker_signal
        - 0.14 * defender_resistance_signal
        + 0.10
        * _round_progress(round_number)
        * defense_decay_signal
    )

    return float(
        np.clip(
            effective_accuracy,
            0.08,
            0.72,
        )
    )



def _apply_opponent_striking_interaction(
    *,
    attacker_profile: FighterSimulationProfile,
    defender_profile: FighterSimulationProfile,
    parameters: ActivityParameters,
    round_number: int,
) -> ActivityParameters:
    """Adjust striking opportunity using defender-relative RFS deltas.

    The suppression-family source columns are signed opponent deltas:

        opponent actual performance - opponent baseline performance

    Therefore:

    - negative values indicate genuine suppression;
    - positive values indicate that opponents exceeded baseline.

    Opponent-output acceleration is also signed. A strongly negative value
    indicates that opponents historically reduced their output as fights
    progressed against this defender.
    """

    opponent_sig_attempt_delta = _profile_value(
        defender_profile,
        "opponent_sig_attempt_suppression",
        default=0.0,
    )
    opponent_sig_accuracy_delta = _profile_value(
        defender_profile,
        "opponent_sig_accuracy_suppression",
        default=0.0,
    )
    opponent_output_acceleration = _profile_value(
        defender_profile,
        "opponent_output_acceleration",
        default=0.0,
    )

    # Convert signed raw deltas into bounded effects.
    #
    # Negative attempt/accuracy deltas become positive suppression signals.
    # Positive deltas become negative signals and modestly increase the
    # attacker's expected opportunity.
    attempt_suppression_signal = float(
        np.tanh(
            -opponent_sig_attempt_delta / 12.0
        )
    )
    accuracy_suppression_signal = float(
        np.tanh(
            -opponent_sig_accuracy_delta / 0.10
        )
    )

    # Negative acceleration means opponents tend to decelerate against this
    # defender. Apply this progressively rather than fully in Round 1.
    output_deceleration_signal = float(
        np.tanh(
            -opponent_output_acceleration / 20.0
        )
    )

    round_progress = _round_progress(round_number)

    attempt_multiplier = float(
        np.clip(
            1.0
            - 0.12 * attempt_suppression_signal
            - 0.18
            * round_progress
            * output_deceleration_signal,
            0.65,
            1.20,
        )
    )

    accuracy_adjustment = float(
        -0.04 * accuracy_suppression_signal
        - 0.03
        * round_progress
        * output_deceleration_signal
    )

    return replace(
        parameters,
        sig_attempt_rate=float(
            np.clip(
                parameters.sig_attempt_rate
                * attempt_multiplier,
                0.75,
                8.0,
            )
        ),
        sig_accuracy=float(
            np.clip(
                parameters.sig_accuracy
                + accuracy_adjustment,
                0.20,
                0.75,
            )
        ),
    )

def _thin_striking_activity(
    *,
    activity: SegmentActivity,
    attempt_multiplier: float,
    power_multiplier: float,
    forced_phase: FightPhase | None,
    rng: np.random.Generator,
) -> SegmentActivity:
    """Reduce striking opportunity after opponent wrestling pressure."""

    attempt_multiplier = float(
        np.clip(attempt_multiplier, 0.0, 1.0)
    )
    power_multiplier = float(
        np.clip(power_multiplier, 0.0, 1.0)
    )

    retained_attempts = int(
        rng.binomial(
            activity.sig_str_attempted,
            attempt_multiplier,
        )
    )

    original_accuracy = (
        activity.sig_str_landed
        / activity.sig_str_attempted
        if activity.sig_str_attempted > 0
        else 0.0
    )

    retained_landed = int(
        rng.binomial(
            retained_attempts,
            float(np.clip(original_accuracy, 0.0, 1.0)),
        )
    )

    # Preserve the fighter's underlying power signal, but reduce how much
    # of it is available while defending wrestling.
    if retained_landed > 0:
        original_kd_per_landed = (
            activity.knockdowns
            / activity.sig_str_landed
            if activity.sig_str_landed > 0
            else 0.0
        )

        adjusted_kd_probability = float(
            np.clip(
                original_kd_per_landed * power_multiplier,
                0.0,
                1.0,
            )
        )

        probability_any_kd = float(
            1.0
            - (
                1.0 - adjusted_kd_probability
            ) ** retained_landed
        )

        retained_knockdowns = int(
            rng.random() < probability_any_kd
        )
    else:
        retained_knockdowns = 0

    adjusted_phase = (
        forced_phase
        if forced_phase is not None
        else activity.phase
    )

    retains_ground_context = (
        adjusted_phase == FightPhase.GROUND
    )
    retains_submission_context = (
        retains_ground_context
        or activity.control_seconds > 0
    )

    return replace(
        activity,
        phase=adjusted_phase,
        sig_str_attempted=retained_attempts,
        sig_str_landed=retained_landed,
        ground_str_attempted=(
            activity.ground_str_attempted
            if retains_ground_context
            else 0
        ),
        ground_str_landed=(
            activity.ground_str_landed
            if retains_ground_context
            else 0
        ),
        submission_attempts=(
            activity.submission_attempts
            if retains_submission_context
            else 0
        ),
        knockdowns=retained_knockdowns,
    )


def _apply_opponent_wrestling_pressure(
    *,
    activity: SegmentActivity,
    opponent_activity: SegmentActivity,
    rng: np.random.Generator,
) -> SegmentActivity:
    """Suppress striking according to opponent TD attempts and success."""

    if opponent_activity.td_landed > 0:
        # A completed takedown sharply removes clean striking opportunity.
        return _thin_striking_activity(
            activity=activity,
            attempt_multiplier=0.35,
            power_multiplier=0.30,
            forced_phase=FightPhase.GROUND,
            rng=rng,
        )

    if opponent_activity.td_attempted > 0:
        # Even failed shots disrupt stance, combinations, and planted power.
        attempt_multiplier = max(
            0.60,
            1.0
            - 0.12 * opponent_activity.td_attempted,
        )
        power_multiplier = max(
            0.55,
            1.0
            - 0.18 * opponent_activity.td_attempted,
        )

        return _thin_striking_activity(
            activity=activity,
            attempt_multiplier=attempt_multiplier,
            power_multiplier=power_multiplier,
            forced_phase=FightPhase.CLINCH,
            rng=rng,
        )

    return activity



def _apply_energy_to_power(
    parameters: ActivityParameters,
    *,
    energy: float,
) -> ActivityParameters:
    """Scale fighter-specific knockdown power by current path energy.

    Full energy preserves the fighter's complete observed power signal.
    Exhaustion reduces power toward a nonzero floor without regressing
    the fighter toward a population-average puncher.
    """

    bounded_energy = float(
        np.clip(
            energy,
            0.0,
            1.0,
        )
    )

    power_multiplier = float(
        0.30 + 0.70 * bounded_energy
    )

    return replace(
        parameters,
        knockdown_probability=float(
            np.clip(
                parameters.knockdown_probability
                * power_multiplier,
                0.0001,
                0.060,
            )
        ),
    )

def generate_matchup_segment(
    *,
    red_profile: FighterSimulationProfile,
    blue_profile: FighterSimulationProfile,
    round_number: int,
    segment_number: int,
    rng: np.random.Generator,
    red_energy: float = 1.0,
    blue_energy: float = 1.0,
) -> SegmentMatchupActivity:
    """Generate red and blue activity for one shared fight segment."""

    red_parameters = build_activity_parameters(
        red_profile,
        round_number=round_number,
    )
    blue_parameters = build_activity_parameters(
        blue_profile,
        round_number=round_number,
    )

    # Resolve each fighter's nominal offense against the opponent's signed
    # suppression and defensive-trajectory profile before sampling activity.
    red_parameters = _apply_opponent_striking_interaction(
        attacker_profile=red_profile,
        defender_profile=blue_profile,
        parameters=red_parameters,
        round_number=round_number,
    )
    blue_parameters = _apply_opponent_striking_interaction(
        attacker_profile=blue_profile,
        defender_profile=red_profile,
        parameters=blue_parameters,
        round_number=round_number,
    )

    red_parameters = _apply_energy_to_power(
        red_parameters,
        energy=red_energy,
    )
    blue_parameters = _apply_energy_to_power(
        blue_parameters,
        energy=blue_energy,
    )

    red_parameters = replace(
        red_parameters,
        td_accuracy=_effective_td_accuracy(
            attacker_profile=red_profile,
            defender_profile=blue_profile,
            base_accuracy=red_parameters.td_accuracy,
            round_number=round_number,
        ),
    )
    blue_parameters = replace(
        blue_parameters,
        td_accuracy=_effective_td_accuracy(
            attacker_profile=blue_profile,
            defender_profile=red_profile,
            base_accuracy=blue_parameters.td_accuracy,
            round_number=round_number,
        ),
    )

    red_activity = generate_segment_activity(
        red_parameters,
        rng,
    )
    blue_activity = generate_segment_activity(
        blue_parameters,
        rng,
    )

    # Apply each fighter's sampled wrestling pressure to the opponent's
    # striking opportunity. Use the original activities so the two
    # adjustments do not recursively affect one another.
    adjusted_red_activity = _apply_opponent_wrestling_pressure(
        activity=red_activity,
        opponent_activity=blue_activity,
        rng=rng,
    )
    adjusted_blue_activity = _apply_opponent_wrestling_pressure(
        activity=blue_activity,
        opponent_activity=red_activity,
        rng=rng,
    )

    return SegmentMatchupActivity(
        round_number=round_number,
        segment_number=segment_number,
        red=adjusted_red_activity,
        blue=adjusted_blue_activity,
    )


def aggregate_segment_activity(
    segments: list[SegmentActivity],
) -> Mapping[str, int]:
    """Aggregate segment activity into round- or fight-level totals."""

    return {
        "sig_str_attempted": sum(
            segment.sig_str_attempted for segment in segments
        ),
        "sig_str_landed": sum(
            segment.sig_str_landed for segment in segments
        ),
        "td_attempted": sum(
            segment.td_attempted for segment in segments
        ),
        "td_landed": sum(
            segment.td_landed for segment in segments
        ),
        "control_seconds": sum(
            segment.control_seconds for segment in segments
        ),
        "ground_str_attempted": sum(
            segment.ground_str_attempted for segment in segments
        ),
        "ground_str_landed": sum(
            segment.ground_str_landed for segment in segments
        ),
        "submission_attempts": sum(
            segment.submission_attempts for segment in segments
        ),
        "knockdowns": sum(
            segment.knockdowns for segment in segments
        ),
    }
