"""Thirty-second activity generation for RFS Monte Carlo V1.

Phase 3 scope:
- choose a fight phase
- generate activity counts for one 30-second segment
- use explicit NumPy random generators
- return immutable segment results

Out of scope:
- dynamic fatigue and damage updates
- finish hazards
- round scoring
- file I/O
- production integration
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Mapping

import numpy as np

from pipeline.simulation.rfs_mc_v1.contracts import (
    FightPhase,
    FighterSimulationProfile,
)


SEGMENT_SECONDS = 30
SEGMENTS_PER_ROUND = 10


class SegmentEngineError(ValueError):
    """Raised when segment inputs are invalid."""


@dataclass(frozen=True)
class SegmentActivity:
    """Activity generated by one fighter during one 30-second segment."""

    phase: FightPhase

    sig_str_attempted: int
    sig_str_landed: int

    td_attempted: int
    td_landed: int

    control_seconds: int

    ground_str_attempted: int
    ground_str_landed: int

    submission_attempts: int
    knockdowns: int

    def __post_init__(self) -> None:
        integer_fields = {
            "sig_str_attempted": self.sig_str_attempted,
            "sig_str_landed": self.sig_str_landed,
            "td_attempted": self.td_attempted,
            "td_landed": self.td_landed,
            "control_seconds": self.control_seconds,
            "ground_str_attempted": self.ground_str_attempted,
            "ground_str_landed": self.ground_str_landed,
            "submission_attempts": self.submission_attempts,
            "knockdowns": self.knockdowns,
        }

        for name, value in integer_fields.items():
            if value < 0:
                raise ValueError(f"{name} cannot be negative")

        if self.sig_str_landed > self.sig_str_attempted:
            raise ValueError(
                "sig_str_landed cannot exceed sig_str_attempted"
            )

        if self.td_landed > self.td_attempted:
            raise ValueError("td_landed cannot exceed td_attempted")

        if self.ground_str_landed > self.ground_str_attempted:
            raise ValueError(
                "ground_str_landed cannot exceed ground_str_attempted"
            )

        if self.control_seconds > SEGMENT_SECONDS:
            raise ValueError(
                f"control_seconds cannot exceed {SEGMENT_SECONDS}"
            )


@dataclass(frozen=True)
class SegmentMatchupActivity:
    """Red and blue activity generated for the same segment."""

    round_number: int
    segment_number: int
    red: SegmentActivity
    blue: SegmentActivity

    def __post_init__(self) -> None:
        if self.round_number <= 0:
            raise ValueError("round_number must be positive")

        if not 1 <= self.segment_number <= SEGMENTS_PER_ROUND:
            raise ValueError(
                f"segment_number must be between 1 and "
                f"{SEGMENTS_PER_ROUND}"
            )


@dataclass(frozen=True)
class ActivityParameters:
    """Directly interpretable parameters used by the activity generator."""

    distance_phase_probability: float
    clinch_phase_probability: float
    ground_phase_probability: float

    sig_attempt_rate: float
    sig_accuracy: float

    td_attempt_rate: float
    td_accuracy: float

    control_probability: float
    mean_control_seconds: float

    ground_attempt_rate: float
    ground_accuracy: float

    submission_attempt_rate: float
    knockdown_probability: float

    def __post_init__(self) -> None:
        probabilities = {
            "distance_phase_probability": (
                self.distance_phase_probability
            ),
            "clinch_phase_probability": self.clinch_phase_probability,
            "ground_phase_probability": self.ground_phase_probability,
            "sig_accuracy": self.sig_accuracy,
            "td_accuracy": self.td_accuracy,
            "control_probability": self.control_probability,
            "ground_accuracy": self.ground_accuracy,
            "knockdown_probability": self.knockdown_probability,
        }

        for name, value in probabilities.items():
            if not 0.0 <= value <= 1.0:
                raise ValueError(f"{name} must be between 0 and 1")

        phase_total = (
            self.distance_phase_probability
            + self.clinch_phase_probability
            + self.ground_phase_probability
        )

        if not np.isclose(phase_total, 1.0):
            raise ValueError(
                "phase probabilities must sum to 1"
            )

        nonnegative = {
            "sig_attempt_rate": self.sig_attempt_rate,
            "td_attempt_rate": self.td_attempt_rate,
            "mean_control_seconds": self.mean_control_seconds,
            "ground_attempt_rate": self.ground_attempt_rate,
            "submission_attempt_rate": self.submission_attempt_rate,
        }

        for name, value in nonnegative.items():
            if value < 0:
                raise ValueError(f"{name} cannot be negative")


DEFAULT_ACTIVITY_PARAMETERS = ActivityParameters(
    distance_phase_probability=0.70,
    clinch_phase_probability=0.15,
    ground_phase_probability=0.15,
    sig_attempt_rate=4.0,
    sig_accuracy=0.45,
    td_attempt_rate=0.30,
    td_accuracy=0.35,
    control_probability=0.30,
    mean_control_seconds=12.0,
    ground_attempt_rate=1.5,
    ground_accuracy=0.50,
    submission_attempt_rate=0.08,
    knockdown_probability=0.015,
)


def _profile_value(
    profile: FighterSimulationProfile,
    name: str,
    *,
    default: float,
) -> float:
    """Read one optional profile value without mutating the profile."""

    estimate = profile.parameters.get(name)
    if estimate is None:
        return default

    value = float(estimate.value)

    if not np.isfinite(value):
        raise SegmentEngineError(
            f"Profile parameter {name!r} is not finite"
        )

    return value


def build_activity_parameters(
    profile: FighterSimulationProfile,
) -> ActivityParameters:
    """Map a fighter profile into initial segment activity parameters.

    These mappings are deliberately conservative placeholders for Phase 3.
    They establish testable mechanics contracts but are not calibrated final
    coefficients.
    """

    phase_disruption = _profile_value(
        profile,
        "phase_mix_disruption",
        default=0.0,
    )
    wrestling_persistence = _profile_value(
        profile,
        "wrestling_persistence",
        default=0.0,
    )
    sig_attempt_trajectory = _profile_value(
        profile,
        "sig_attempt_trajectory",
        default=0.0,
    )
    sig_accuracy_trajectory = _profile_value(
        profile,
        "sig_accuracy_trajectory",
        default=0.0,
    )
    control_per_td_attempt = _profile_value(
        profile,
        "control_per_td_attempt",
        default=0.0,
    )
    control_to_damage = _profile_value(
        profile,
        "control_to_damage",
        default=0.0,
    )
    submission_pressure = _profile_value(
        profile,
        "submission_pressure",
        default=0.0,
    )
    knockdowns_absorbed = _profile_value(
        profile,
        "knockdowns_absorbed",
        default=0.0,
    )

    ground_probability = float(
        np.clip(
            0.15
            + 0.03 * wrestling_persistence
            + 0.01 * phase_disruption,
            0.05,
            0.50,
        )
    )

    clinch_probability = float(
        np.clip(
            0.15 + 0.01 * phase_disruption,
            0.05,
            0.35,
        )
    )

    distance_probability = 1.0 - (
        ground_probability + clinch_probability
    )

    if distance_probability < 0.05:
        excess = 0.05 - distance_probability
        ground_probability = max(
            0.05,
            ground_probability - excess,
        )
        distance_probability = 0.05

    phase_total = (
        distance_probability
        + clinch_probability
        + ground_probability
    )

    distance_probability /= phase_total
    clinch_probability /= phase_total
    ground_probability /= phase_total

    sig_attempt_rate = float(
        np.clip(
            4.0 + 0.20 * sig_attempt_trajectory,
            0.10,
            15.0,
        )
    )

    sig_accuracy = float(
        np.clip(
            0.45 + 0.02 * sig_accuracy_trajectory,
            0.05,
            0.90,
        )
    )

    td_attempt_rate = float(
        np.clip(
            0.30 + 0.05 * wrestling_persistence,
            0.0,
            3.0,
        )
    )

    mean_control_seconds = float(
        np.clip(
            8.0 + 0.05 * control_per_td_attempt,
            0.0,
            SEGMENT_SECONDS,
        )
    )

    ground_attempt_rate = float(
        np.clip(
            1.0 + 0.25 * control_to_damage,
            0.0,
            10.0,
        )
    )

    submission_attempt_rate = float(
        np.clip(
            0.05 + 0.03 * submission_pressure,
            0.0,
            2.0,
        )
    )

    knockdown_probability = float(
        np.clip(
            0.015 + 0.002 * knockdowns_absorbed,
            0.0,
            0.20,
        )
    )

    return ActivityParameters(
        distance_phase_probability=distance_probability,
        clinch_phase_probability=clinch_probability,
        ground_phase_probability=ground_probability,
        sig_attempt_rate=sig_attempt_rate,
        sig_accuracy=sig_accuracy,
        td_attempt_rate=td_attempt_rate,
        td_accuracy=0.35,
        control_probability=0.30,
        mean_control_seconds=mean_control_seconds,
        ground_attempt_rate=ground_attempt_rate,
        ground_accuracy=0.50,
        submission_attempt_rate=submission_attempt_rate,
        knockdown_probability=knockdown_probability,
    )


def sample_phase(
    parameters: ActivityParameters,
    rng: np.random.Generator,
) -> FightPhase:
    """Sample the dominant phase for one fighter in one segment."""

    phases = np.array(
        [
            FightPhase.DISTANCE,
            FightPhase.CLINCH,
            FightPhase.GROUND,
        ],
        dtype=object,
    )

    probabilities = np.array(
        [
            parameters.distance_phase_probability,
            parameters.clinch_phase_probability,
            parameters.ground_phase_probability,
        ],
        dtype=float,
    )

    return rng.choice(phases, p=probabilities)


def generate_segment_activity(
    parameters: ActivityParameters,
    rng: np.random.Generator,
) -> SegmentActivity:
    """Generate one fighter's activity for one 30-second segment."""

    phase = sample_phase(parameters, rng)

    sig_multiplier = {
        FightPhase.DISTANCE: 1.00,
        FightPhase.CLINCH: 0.65,
        FightPhase.GROUND: 0.35,
    }[phase]

    td_multiplier = {
        FightPhase.DISTANCE: 0.70,
        FightPhase.CLINCH: 1.40,
        FightPhase.GROUND: 0.15,
    }[phase]

    sig_attempted = int(
        rng.poisson(
            parameters.sig_attempt_rate * sig_multiplier
        )
    )

    sig_str_landed = int(
        rng.binomial(
            sig_attempted,
            parameters.sig_accuracy,
        )
    )

    td_attempted = int(
        rng.poisson(
            parameters.td_attempt_rate * td_multiplier
        )
    )

    td_landed = int(
        rng.binomial(
            td_attempted,
            parameters.td_accuracy,
        )
    )

    control_seconds = 0
    if (
        phase is FightPhase.GROUND
        or td_landed > 0
    ) and rng.random() < parameters.control_probability:
        sampled_control = rng.exponential(
            parameters.mean_control_seconds
        )
        control_seconds = int(
            np.clip(
                round(sampled_control),
                0,
                SEGMENT_SECONDS,
            )
        )

    ground_str_attempted = 0
    ground_str_landed = 0
    submission_attempts = 0

    if phase is FightPhase.GROUND or control_seconds > 0:
        ground_str_attempted = int(
            rng.poisson(parameters.ground_attempt_rate)
        )
        ground_str_landed = int(
            rng.binomial(
                ground_str_attempted,
                parameters.ground_accuracy,
            )
        )
        submission_attempts = int(
            rng.poisson(parameters.submission_attempt_rate)
        )

    knockdowns = int(
        sig_str_landed > 0
        and rng.random() < parameters.knockdown_probability
    )

    return SegmentActivity(
        phase=phase,
        sig_str_attempted=sig_attempted,
        sig_str_landed=sig_str_landed,
        td_attempted=td_attempted,
        td_landed=td_landed,
        control_seconds=control_seconds,
        ground_str_attempted=ground_str_attempted,
        ground_str_landed=ground_str_landed,
        submission_attempts=submission_attempts,
        knockdowns=knockdowns,
    )


def generate_matchup_segment(
    *,
    red_profile: FighterSimulationProfile,
    blue_profile: FighterSimulationProfile,
    round_number: int,
    segment_number: int,
    rng: np.random.Generator,
) -> SegmentMatchupActivity:
    """Generate red and blue activity for one shared fight segment."""

    red_parameters = build_activity_parameters(red_profile)
    blue_parameters = build_activity_parameters(blue_profile)

    return SegmentMatchupActivity(
        round_number=round_number,
        segment_number=segment_number,
        red=generate_segment_activity(red_parameters, rng),
        blue=generate_segment_activity(blue_parameters, rng),
    )


def aggregate_segment_activity(
    segments: list[SegmentActivity],
) -> Mapping[str, int]:
    """Aggregate segment activity into round- or fight-level totals."""

    return {
        "sig_str_attempted": sum(
            segment.sig_str_attempted for segment in segments
        ),
        "sig_str_landed": sum(
            segment.sig_str_landed for segment in segments
        ),
        "td_attempted": sum(
            segment.td_attempted for segment in segments
        ),
        "td_landed": sum(
            segment.td_landed for segment in segments
        ),
        "control_seconds": sum(
            segment.control_seconds for segment in segments
        ),
        "ground_str_attempted": sum(
            segment.ground_str_attempted for segment in segments
        ),
        "ground_str_landed": sum(
            segment.ground_str_landed for segment in segments
        ),
        "submission_attempts": sum(
            segment.submission_attempts for segment in segments
        ),
        "knockdowns": sum(
            segment.knockdowns for segment in segments
        ),
    }
