name: Run Live Predictions

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: write

jobs:
  run-live-prediction:
    runs-on: ubuntu-latest

    steps:

      # ------------------------------------------------------
      # Checkout repo
      # ------------------------------------------------------

      - name: Checkout repo
        uses: actions/checkout@v4

      # ------------------------------------------------------
      # Python setup
      # ------------------------------------------------------

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # ------------------------------------------------------
      # Install Chrome for Selenium
      # ------------------------------------------------------

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb

          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      # ------------------------------------------------------
      # Install Python dependencies
      # ------------------------------------------------------

      - name: Install dependencies
        run: |
          pip install pandas
          pip install numpy
          pip install requests
          pip install pyarrow
          pip install joblib
          pip install scikit-learn==1.6.1
          pip install xgboost
          pip install beautifulsoup4
          pip install lxml
          pip install selenium
          pip install webdriver-manager

      # ------------------------------------------------------
      # Run live prediction pipeline
      # ------------------------------------------------------

      - name: Run live prediction pipeline
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: |
          python run_live_prediction.py

      # ------------------------------------------------------
      # Commit updated outputs
      # ------------------------------------------------------

      - name: Commit updated parquet files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add *.parquet
          git commit -m "Automated CLV update" || echo "No changes to commit"

          git pull --rebase --autostash origin main

          git push
